// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLock.Services.AccessRight.Data;

namespace SmartLock.Services.AccessRight.API.Migrations
{
    [DbContext(typeof(AccessRightDbContext))]
    [Migration("20180716100628_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartLock.Services.AccessRight.Model.AccessRight", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("LockId");

                    b.Property<bool>("HasAccess");

                    b.HasKey("UserId", "LockId");

                    b.HasAlternateKey("LockId", "UserId");

                    b.ToTable("AccessRights");
                });
#pragma warning restore 612, 618
        }
    }
}
