// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLock.Services.Managment.API.Data;

namespace SmartLock.Services.Managment.API.Migrations
{
    [DbContext(typeof(ManagmentDbContext))]
    partial class ManagmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.AccessRight", b =>
                {
                    b.Property<Guid>("AccessRightId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AccessorId");

                    b.Property<bool>("HasAccess");

                    b.HasKey("AccessRightId");

                    b.HasIndex("AccessorId");

                    b.ToTable("AccessRights");
                });

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.Lock", b =>
                {
                    b.Property<Guid>("LockId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("Status");

                    b.HasKey("LockId");

                    b.ToTable("Locks");
                });

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<Guid?>("UserGroupId");

                    b.HasKey("UserId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.UserGroup", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("UserGroupId");

                    b.ToTable("UserGroup");
                });

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.UserGroupMember", b =>
                {
                    b.Property<Guid>("UserGroupMemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("UserGroupId");

                    b.Property<Guid>("UserId");

                    b.HasKey("UserGroupMemberId");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupMember");
                });

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.AccessRight", b =>
                {
                    b.HasOne("SmartLock.Services.Managment.API.Model.UserGroup", "UserGroup")
                        .WithMany("AccessRights")
                        .HasForeignKey("AccessorId");

                    b.HasOne("SmartLock.Services.Managment.API.Model.User", "User")
                        .WithMany("AccessRights")
                        .HasForeignKey("AccessorId");
                });

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.User", b =>
                {
                    b.HasOne("SmartLock.Services.Managment.API.Model.UserGroup")
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId");
                });

            modelBuilder.Entity("SmartLock.Services.Managment.API.Model.UserGroupMember", b =>
                {
                    b.HasOne("SmartLock.Services.Managment.API.Model.UserGroup", "UserGroup")
                        .WithMany("UserGroupMembers")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartLock.Services.Managment.API.Model.User", "User")
                        .WithMany("UserGroupMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
