// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLock.Services.AuditLogs.API.Data;

namespace SmartLock.Services.AuditLogs.API.Migrations
{
    [DbContext(typeof(AuditLogDbContext))]
    [Migration("20180703065726_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("SmartLock.Services.AuditLogs.API.Model.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("CommandResult")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<Guid>("LockId");

                    b.Property<string>("LockName")
                        .IsRequired();

                    b.Property<DateTime>("RequestDate");

                    b.Property<Guid>("UserId");

                    b.Property<string>("UserNameFamily")
                        .IsRequired();

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLog");
                });
#pragma warning restore 612, 618
        }
    }
}
