// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLock.Services.AuditLogs.API.Data;

namespace SmartLock.Services.AuditLogs.API.Migrations
{
    [DbContext(typeof(AuditLogDbContext))]
    partial class AuditLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartLock.Services.AuditLogs.API.Model.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("CommandResult")
                        .HasMaxLength(20);

                    b.Property<Guid>("LockId");

                    b.Property<string>("LockName");

                    b.Property<DateTime>("RequestDate");

                    b.Property<Guid>("UserId");

                    b.Property<string>("UserNameFamily");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLog");
                });
#pragma warning restore 612, 618
        }
    }
}
